# Generated by Django 5.2 on 2025-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slug_quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
                ('take_again', models.CharField(max_length=10)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
